/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StatsDescDial.java
 *
 * Created on 17 nov. 2011, 17:38:04
 */

package inpresferriesclientfreetax_XML;

import java.io.BufferedWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.Calendar;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Sh1fT
 */

public final class StatsDescDial extends javax.swing.JDialog {
    protected Client_IFreetax client_IFreetax;
    protected Boolean graph;
    protected String dimGraph;
    protected String typeGraph;

    /**
     * Creates new form StatsDescDial
     * @param parent
     * @param modal
     * @param graph
     * @param dimGraph
     * @param typeGraph 
     */
    public StatsDescDial(Client_IFreetax parent, boolean modal, boolean graph,
        String dimGraph, String typeGraph) {
        super(parent, modal);
        this.initComponents();
        this.setClient_IFreetax(parent);
        this.setGraph(graph);
        this.setDimGraph(dimGraph);
        this.setTypeGraph(typeGraph);
    }

    public Client_IFreetax getClient_IFreetax() {
        return this.client_IFreetax;
    }

    protected void setClient_IFreetax(Client_IFreetax client_IFreetax) {
        this.client_IFreetax = client_IFreetax;
    }

    public Boolean getGraph() {
        return this.graph;
    }

    protected void setGraph(Boolean graph) {
        this.graph = graph;
    }

    public String getDimGraph() {
        return this.dimGraph;
    }

    protected void setDimGraph(String dimGraph) {
        this.dimGraph = dimGraph;
    }

    public String getTypeGraph() {
        return this.typeGraph;
    }

    protected void setTypeGraph(String typeGraph) {
        this.typeGraph = typeGraph;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        semaineRadioButton = new javax.swing.JRadioButton();
        categorieComboBox = new javax.swing.JComboBox();
        moisRadioButton = new javax.swing.JRadioButton();
        semaineSpinner = new javax.swing.JSpinner();
        moisSpinner = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        sumLabel = new javax.swing.JLabel();
        sumWeekMonthLabel = new javax.swing.JLabel();
        avgWeekMonthLabel = new javax.swing.JLabel();
        modeWeekMonthLabel = new javax.swing.JLabel();
        sddWeekMonthLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Client_IFreetax - StatsDescDial");
        setModal(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Choix"));

        jLabel1.setText("Catégorie :");

        semaineRadioButton.setSelected(true);
        semaineRadioButton.setText("Semaine :");
        buttonGroup1.add(semaineRadioButton);

        categorieComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alcool", "Tabac", "Parfumerie" }));

        moisRadioButton.setText("Mois :");
        buttonGroup1.add(moisRadioButton);

        SpinnerModel semaineModel = new SpinnerNumberModel(1, 1, Calendar.getInstance().getActualMaximum(Calendar.DAY_OF_MONTH), 1);
        semaineSpinner.setModel(semaineModel);

        SpinnerModel moisModel = new SpinnerNumberModel(1, 1, 12, 1);
        moisSpinner.setModel(moisModel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(semaineRadioButton)
                    .addComponent(jLabel1)
                    .addComponent(moisRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categorieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(moisSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(semaineSpinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(categorieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semaineRadioButton)
                    .addComponent(semaineSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moisRadioButton)
                    .addComponent(moisSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jButton1)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Résultats"));
        jPanel3.setVisible(false);

        sumLabel.setFont(new java.awt.Font("Tahoma", 2, 11));
        sumLabel.setText("unknown");

        sumWeekMonthLabel.setFont(new java.awt.Font("Tahoma", 2, 11));
        sumWeekMonthLabel.setText("unknown");

        avgWeekMonthLabel.setFont(new java.awt.Font("Tahoma", 2, 11));
        avgWeekMonthLabel.setText("unknown");

        modeWeekMonthLabel.setFont(new java.awt.Font("Tahoma", 2, 11));
        modeWeekMonthLabel.setText("unknown");

        sddWeekMonthLabel.setFont(new java.awt.Font("Tahoma", 2, 11));
        sddWeekMonthLabel.setText("unknown");

        jLabel2.setText("Somme des produits :");

        jLabel3.setText("Somme des produits de la période :");

        jLabel4.setText("Moyenne des produits de la période :");

        jLabel5.setText("Mode des produits de la période :");

        jLabel6.setText("Ecart-type des produits de la période :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sumWeekMonthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avgWeekMonthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modeWeekMonthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sddWeekMonthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sumWeekMonthLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(avgWeekMonthLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(modeWeekMonthLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sddWeekMonthLabel)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Socket socket = new Socket(this.getClient_IFreetax().getServerHost(),
                this.getClient_IFreetax().getServerPort());
            ObjectInputStream ois = new ObjectInputStream(socket.getInputStream());
            PrintWriter pw = new PrintWriter(new BufferedWriter(
                new OutputStreamWriter(socket.getOutputStream())), true);
            String category = this.categorieComboBox.getSelectedItem().toString();
            String week = null;
            String month = null;
            if (this.semaineRadioButton.isSelected()) {
                week = this.semaineSpinner.getValue().toString();
                month = "unknown";
            } else {
                week = "unknown";
                month = this.moisSpinner.getValue().toString();
            }
            if (!this.getGraph()) {
                String commande = "GET_STATISTICS_DESCR";
                pw.println(commande + ";" + category + ";" + week + ";" + month);
                String infos = ois.readObject().toString();
                StringTokenizer st  = new StringTokenizer(infos, ";");
                this.sumLabel.setText(st.nextToken());
                this.sumWeekMonthLabel.setText(st.nextToken());
                this.avgWeekMonthLabel.setText(st.nextToken());
                this.modeWeekMonthLabel.setText(st.nextToken());
                this.sddWeekMonthLabel.setText(st.nextToken());
                this.jPanel3.setVisible(true);
                this.pack();
            } else {
                if (this.getDimGraph().compareTo("1D") == 0) {
                    String commande = "GET_GRAPH_1D";
                    pw.println(commande + ";" + category + ";" + week + ";" +
                        month + ";" + this.getTypeGraph());
                    ImageIcon ic = (ImageIcon) ois.readObject();
                    new Graph(this, true, ic).setVisible(true);
                } else if (this.getDimGraph().compareTo("2D") == 0) {
                    String commande = "GET_GRAPH_2D";
                    pw.println(commande + ";" + category + ";" + week + ";" +
                        month + ";" + this.getTypeGraph());
                    ImageIcon ic = (ImageIcon) ois.readObject();
                    new Graph(this, true, ic).setVisible(true);
                }
            }
            pw.close();
            ois.close();
            socket.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(),
                    "Aïe Aïe Aïe !", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(),
                    "Aïe Aïe Aïe !", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatsDescDial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatsDescDial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatsDescDial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatsDescDial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                StatsDescDial dialog = new StatsDescDial(new Client_IFreetax(), true, false, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avgWeekMonthLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox categorieComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel modeWeekMonthLabel;
    private javax.swing.JRadioButton moisRadioButton;
    private javax.swing.JSpinner moisSpinner;
    private javax.swing.JLabel sddWeekMonthLabel;
    private javax.swing.JRadioButton semaineRadioButton;
    private javax.swing.JSpinner semaineSpinner;
    private javax.swing.JLabel sumLabel;
    private javax.swing.JLabel sumWeekMonthLabel;
    // End of variables declaration//GEN-END:variables
}